"""initial migration

Revision ID: 6e79cd410585
Revises: 
Create Date: 2021-09-03 02:56:03.209010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e79cd410585'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Stock',
    sa.Column('StockId', sa.Integer(), nullable=False),
    sa.Column('StockName', sa.String(length=50), nullable=False),
    sa.Column('PriceNow', sa.Float(), nullable=False),
    sa.Column('VolumeNow', sa.Float(), nullable=False),
    sa.Column('VolumeAll', sa.Float(), nullable=False),
    sa.Column('OpenPrice', sa.Float(), nullable=False),
    sa.Column('HighestPrice', sa.Float(), nullable=False),
    sa.Column('LowestPrice', sa.Float(), nullable=False),
    sa.Column('ClosingPrice', sa.Float(), nullable=False),
    sa.Column('Increase', sa.Float(), nullable=False),
    sa.Column('Amplitude', sa.Float(), nullable=False),
    sa.Column('Updown', sa.Float(), nullable=False),
    sa.Column('FavoriteCount', sa.Integer(), nullable=False),
    sa.Column('CreateTime', sa.DateTime(), nullable=False),
    sa.Column('UpdateTime', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('StockId'),
    sa.UniqueConstraint('StockName')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Stock')
    # ### end Alembic commands ###
